# Generated by Django 2.2.1 on 2019-06-16 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.IntegerField()),
                ('comentario', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=70)),
                ('creado', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('video', models.CharField(max_length=150, null=True)),
                ('reseña', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='caratulas/')),
            ],
        ),
    ]
