# Generated by Django 2.2.1 on 2019-06-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20190625_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='N3DS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='NSWITCH',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='PC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='PS3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='PS4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='XBOX360',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='XBOXONE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='juego',
            name='p',
            field=models.CharField(default=int, max_length=150),
            preserve_default=False,
        ),
    ]
